Repository acm-ucr/naama-website, pull requests merged in 2025-04, with the labels that each got.

#4 Add event images and board group photo
  public/board/groupBoard.webp
  public/gallery/image1.webp
  public/gallery/image10.webp
  public/gallery/image11.webp
  public/gallery/image12.webp
  public/gallery/image13.webp
  public/gallery/image15.webp
  public/gallery/image16.webp
  public/gallery/image17.webp
  public/gallery/image18.webp
  public/gallery/image19.webp
  public/gallery/image2.webp
  public/gallery/image3.webp
  public/gallery/image4.webp
  public/gallery/image5.webp
  public/gallery/image6.webp
  public/gallery/image8.webp
  public/gallery/image9.webp
  public/gallery/presidents.webp
Labels: enhancement

#22 Fix security vulnerability, update husky command
  package-lock.json
  package.json
Labels: bug

#26 feat: add footer
  public/logo.svg
  public/logo.webp
  src/app/page.tsx
  src/components/Footer.tsx
Labels: ready to review

#25 Jsimj001/redirect button component
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/Button.tsx
Labels: ready to review

#35 Font fix
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Example.tsx
Labels: ready to review

#37 Pineapple soup/navbar
  src/app/page.tsx
  src/components/Footer.tsx
  src/components/NavBar.tsx
Labels: ready to review

#34 Join Us Card Component
  src/app/page.tsx
  src/components/home/JoinCard.tsx
  src/components/home/JoinUs.tsx
Labels: ready to review, address comments

#45 Explore Our Events Tab
  src/app/about/page.tsx
  src/components/home/ExploreOurEvents.tsx
  src/components/home/GetInvolved.tsx
Labels: ready to review

#44 Ting/components
  package.json
  src/app/about/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/Footer.tsx
  src/components/NavBar.tsx
  src/components/about/GetInvolved.tsx
  src/components/home/ExploreOurEvents.tsx
  src/components/home/Feed.tsx
  src/components/home/GetInvolved.tsx
  src/components/home/JoinCard.tsx
Labels: ready to review

#48 About Us Page merge conflict resolved
  package-lock.json
  src/app/about/page.tsx
  src/components/about/About.tsx
Labels: ready to review, address comments

#47 Pineapple soup/joincommunity
  src/app/gallery/page.tsx
  src/app/page.tsx
  src/components/Button.tsx
  src/components/home/JoinCommunity.tsx
Labels: ready to review
