Repository acm-ucr/naama-website, pull requests merged in 2025-05, with the labels that each got.

#41 Added come join us part
  src/app/page.tsx
  src/components/home/ComeJoinUs.tsx
Labels: ready to review

#36 Mostafa title component
  src/app/board/page.tsx
  src/app/calendar/page.tsx
  src/app/gallery/page.tsx
  src/components/Title.tsx
Labels: address comments

#55 hyacinth237/map_navbar
  src/components/NavBar.tsx
  src/data/links.ts
Labels: address comments

#40 Jsimj001/board card component
  public/board/Alexis_Battikha.webp
  public/board/Joelle_Nana.webp
  public/board/Mariam_Abbas.webp
  public/board/Ranya_Butrus.webp
  public/board/Raymon_Marcos.webp
  public/board/Shams_Alsammarraie.webp
  public/board/groupBoard.webp
  src/app/board/page.tsx
  src/components/BoardCard.tsx
Labels: ready to review

#61 Added links requested
  src/components/Footer.tsx
Labels: ready to review

#62 Pineapple soup/gallery
  src/app/board/page.tsx
  src/app/gallery/page.tsx
  src/components/gallery/JoinCommunity.tsx
  src/components/gallery/PictureGallery.tsx
  src/components/home/CircularText.tsx
  src/components/home/Hero.tsx
  src/data/gallery.ts
Labels: gallery page, ready to review

#60 Who We Are Component
  src/components/home/WhoAreWe.tsx
Labels: address comments

#73 Hyacinth237/join us mobile
  src/components/home/ComeJoinUs.tsx
  src/components/home/JoinCard.tsx
  src/components/home/JoinUs.tsx
Labels: ready to review

#72 Moments Component
  src/app/gallery/page.tsx
  src/components/Title.tsx
Labels: good first issue, gallery page, events page

#77 Pineapplesoup/mobile navbar
  src/components/NavBar.tsx
Labels: ready to review

#79 Working Responsiveness
  src/components/home/Hero.tsx
Labels: ready to review

#78 Explore Our Events Mobile Responsiveness
  src/components/about/ExploreOurEvents.tsx
Labels: ready to review, address comments

#87 Pineapplesoup/mobile joincommunity
  src/components/gallery/JoinCommunity.tsx
Labels: gallery page, ready to review, mobile responsiveness

#88 Event Calender Header
  src/app/calendar/page.tsx
Labels: events page, address comments
